### ISSUE TITLE
Simulated data fixes

### ISSUE THREAD

**Issue by youngsaver** [youngsaver/opensdp_equity_report_template#1]
![image](https://user-images.githubusercontent.com/23269462/41379454-fd5dbba6-6f2f-11e8-95f9-a454fdeacd77.png)

1. Currently there are 402,022 observations. This makes sense for the state-level data, but I think we're trying to mimic the slice of the data that the district would get from the state education agency. So, I think the number of observations can be significantly reduced.
2. We should save the data file as a .csv ("synth_texas.csv"), since that is the file format districts receive from the state.
3. Grade level: should be between grades 3 and 8
4. School code: should be 9 digits
5. Student ID: should be 9 digits
6. Sex: Should include levels (M,F); rather than "Male" and "Female"
7. Race-Ethnicity: Should have levels (H,I,A,B,P,W,T,N); rather than full ethnicity spelled out
8. Eco-Dis: Is a factor that includes levels (1,2,9,0); currently only includes (1,0)
9. LEP: Is a factor that includes levels (C,F,S,0); currently only includes (1,0)
10. Reading Scale Score and Math Scale Score: currently both include negative values. I didn't include ranges on definitions document because they vary year-to-year and they vary by grade level. All 2018 scale scores can be found in the documents listed here: https://tea.texas.gov/Student_Testing_and_Accountability/Accountability/State_Accountability/Performance_Reporting/STAAR_Raw_Score_Conversion_Tables_for_2017%E2%80%932018/
11. Title 1, Migrant, Writing Sale Score, Composition: All do not yet have data. Note that we should only have Writing Score and Composition data for grade 4 and grade 7 students (since those are the only years Texas students take a writing test).

**Comment by jknowles** [comment]
What do levels "C", "F", "S" mean for LEP and what do levels "1", "2", and "9" mean for Eco-dis?

**Comment by youngsaver** [comment]
The legend is provided in the data definitions doc: https://github.com/youngsaver/opensdp_equity_report_template/blob/master/man/texas_data_features/data_definitions.md

For LEP: 
C = Student is currently identified as LEP 
F = Student has met criteria for bilingual/ESL program exit, is no longer classified as LEP in TSDS PEIMS, and is in first year of monitoring 
S = Student in second year of monitoring 
0 = Other Non-LEP student

For Eco_Dis:
1 = Eligible for free meals under the National School Lunch and Child Nutrition Program 
2 = Eligible for reduced-price meals under the National School Lunch and Child Nutrition Program 
9 = Other economic disadvantage 
0 = Not identified as economically disadvantaged

**Comment by youngsaver** [comment]
In addition to the above, it'd be great to make the data such that the most severe gap is the gender gap in 8th grade math tests. That is one area that practitioners focus on: it'd be good in terms of the demonstration and would provided a good test of the function to see if it could pick up that gap as the widest gap. Once we have that ready, I will also be able to add more descriptive analysis (words) into the tutorial, since I'll be able to describe the finalized graphics and results.
