### ISSUE TITLE
Improvements to make to gaps function

### ISSUE THREAD

**Issue by youngsaver** [youngsaver/opensdp_equity_report_template#6]
1. Right now, it has no way of prioritizing gaps that affect a larger number of students. For example, if it finds a large gap that affects only 50 students in our population, it will prioritize that over a slightly smaller gap that affects 25,000 students. Maybe that should be considered in its prioritizing. Or, at least, it should report the number of students involved.
2. The output is currently a set of graphics--do we also want to create a manipulable output?
3. The function input of the standard deviation table must be of a certain strict format/layout for the function to work--the function could be made to be more forgiving of formatting differences or more documentation should be done about the specifics of the input table format.

**Comment by jknowles** [comment]
And, currently, this file is not included in the repository: `standard.devsr <- read.csv("../data/sd_table.csv")
`
We should have a fall back if this information doesn't exist, but also strongly specify how the user is to provide it.

**Comment by youngsaver** [comment]
Resolved #3, as now the function will provide error messages if standard deviations not in correct format and provide information about what format fixes are needed. If not standard deviations are provided, the function now calculates the standard deviations from the data given.

**Comment by youngsaver** [comment]
Resolved point (1) above: added an optional argument that allows the user to set a "cut point." If there is a gap that containing a number of students below whatever cut point is set, the function ignores that gap. If no cut point is given, the function treats all gaps equally.

**Comment by youngsaver** [comment]
Resolved point (2) as function now outputs a table that is used directly by the equity report code.
