### ISSUE TITLE
Reducing the volume of figures in the final report

### ISSUE THREAD

**Issue by jknowles** [youngsaver/opensdp_equity_report_template#7]
We don't want to overwhelm the user with every look at the data. We have two alternatives to making the overall report less long vertically (i.e. require less scrolling). 

One option is to combine some of the plots together. The boxplots and histograms are not that information dense, so a lot of times you could fit two of them together into a single plot. This is the easiest approach and it will make the report still compatible with PDF output, etc.

I think the current state-of-the-art best way to do this in R is with this package: https://github.com/thomasp85/patchwork

Another alternative is to use Shiny components or Plotly and make the graphics interactive. This will prevent the report from being output to PDF, but it would allow anyone with a web browser to dynamically select the graphs that correspond to the data elements (such as grade level or student subgroup) that are of interest to them. 

I like this approach because it is web first - but we should turn to it after we have implemented the first approach anyway.

**Comment by youngsaver** [comment]
Report now utilizes gap.test and has cut down on "scrolling" by focusing on one demographic difference in one grade level in one subject area. The amount of graphics has been greatly reduced. However, report still has functionality to do much more.
